name: 'Download localization files'
description: 'Download localization files from SimpleLocalize translation editor'
author: "SimpleLocalize"
branding:
  icon: 'download-cloud'
  color: 'blue'
inputs:
  apiKey:
    description: 'Project API Key'
    required: true
    default: ''
  downloadPath:
    description: 'Where files should be downloaded'
    required: false
    default: './messages.json'
  downloadFormat:
    description: 'Choose a localization files format'
    required: false
    default: 'multi-language-json'
  downloadOptions:
    description: 'Choose additional download options'
    required: false
    default: ''
  languageKey:
    description: 'Download translations for only one language key'
    required: false
    default: ''
  customerId:
    description: 'Download translations for given customerId'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - id: Setup
      run: curl -s https://get.simplelocalize.io/2.0/install | bash
      shell: bash
    - id: Execution
      shell: bash
      run: simplelocalize download --apiKey ${{ inputs.apiKey }} --downloadPath ${{ inputs.downloadPath }} --downloadFormat ${{ inputs.downloadFormat }} ${{ inputs.downloadOptions && '--downloadOptions' }} ${{ inputs.downloadOptions }} ${{ inputs.languageKey && '--languageKey' }} ${{ inputs.languageKey }} ${{ inputs.customerId && '--customerId' }} ${{ inputs.customerId }}
